/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.node;

import br.ufal.ic.se.analysis.*;

public class AAndsentenceComplexsentence extends PComplexsentence
{
    private PSentence _left_;
    private TAnd _and_;
    private PSentence _right_;

    public AAndsentenceComplexsentence()
    {
    }

    public AAndsentenceComplexsentence(
        PSentence _left_,
        TAnd _and_,
        PSentence _right_)
    {
        setLeft(_left_);

        setAnd(_and_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new AAndsentenceComplexsentence(
            (PSentence) cloneNode(_left_),
            (TAnd) cloneNode(_and_),
            (PSentence) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndsentenceComplexsentence(this);
    }

    public PSentence getLeft()
    {
        return _left_;
    }

    public void setLeft(PSentence node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TAnd getAnd()
    {
        return _and_;
    }

    public void setAnd(TAnd node)
    {
        if(_and_ != null)
        {
            _and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _and_ = node;
    }

    public PSentence getRight()
    {
        return _right_;
    }

    public void setRight(PSentence node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_and_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_and_ == child)
        {
            _and_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PSentence) newChild);
            return;
        }

        if(_and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PSentence) newChild);
            return;
        }

    }
}
