/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.node;

import java.util.*;
import br.ufal.ic.se.analysis.*;

public class ABentailssentenceComplexsentence extends PComplexsentence
{
    private PSentence _left_;
    private TBidientails _bidientails_;
    private PSentence _right_;

    public ABentailssentenceComplexsentence()
    {
    }

    public ABentailssentenceComplexsentence(
        PSentence _left_,
        TBidientails _bidientails_,
        PSentence _right_)
    {
        setLeft(_left_);

        setBidientails(_bidientails_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new ABentailssentenceComplexsentence(
            (PSentence) cloneNode(_left_),
            (TBidientails) cloneNode(_bidientails_),
            (PSentence) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABentailssentenceComplexsentence(this);
    }

    public PSentence getLeft()
    {
        return _left_;
    }

    public void setLeft(PSentence node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TBidientails getBidientails()
    {
        return _bidientails_;
    }

    public void setBidientails(TBidientails node)
    {
        if(_bidientails_ != null)
        {
            _bidientails_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _bidientails_ = node;
    }

    public PSentence getRight()
    {
        return _right_;
    }

    public void setRight(PSentence node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_bidientails_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_bidientails_ == child)
        {
            _bidientails_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PSentence) newChild);
            return;
        }

        if(_bidientails_ == oldChild)
        {
            setBidientails((TBidientails) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PSentence) newChild);
            return;
        }

    }
}
