/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.node;

import br.ufal.ic.se.analysis.*;

public final class Start extends Node
{
    private PSentence _pSentence_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PSentence _pSentence_,
        EOF _eof_)
    {
        setPSentence(_pSentence_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PSentence) cloneNode(_pSentence_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PSentence getPSentence()
    {
        return _pSentence_;
    }

    public void setPSentence(PSentence node)
    {
        if(_pSentence_ != null)
        {
            _pSentence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pSentence_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pSentence_ == child)
        {
            _pSentence_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pSentence_ == oldChild)
        {
            setPSentence((PSentence) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pSentence_) +
            toString(_eof_);
    }
}
