/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.node;

import java.util.*;
import br.ufal.ic.se.analysis.*;

public class ASymbolAtomicsentence extends PAtomicsentence
{
    private TLetter _letter_;

    public ASymbolAtomicsentence()
    {
    }

    public ASymbolAtomicsentence(
        TLetter _letter_)
    {
        setLetter(_letter_);

    }
    public Object clone()
    {
        return new ASymbolAtomicsentence(
            (TLetter) cloneNode(_letter_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASymbolAtomicsentence(this);
    }

    public TLetter getLetter()
    {
        return _letter_;
    }

    public void setLetter(TLetter node)
    {
        if(_letter_ != null)
        {
            _letter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _letter_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_letter_);
    }

    void removeChild(Node child)
    {
        if(_letter_ == child)
        {
            _letter_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_letter_ == oldChild)
        {
            setLetter((TLetter) newChild);
            return;
        }

    }
}
