/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.node;

import br.ufal.ic.se.analysis.*;

public final class TEntails extends Token
{
    public TEntails()
    {
        super.setText("=>");
    }

    public TEntails(int line, int pos)
    {
        super.setText("=>");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TEntails(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEntails(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TEntails text.");
    }
}
