/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.node;

import br.ufal.ic.se.analysis.*;

public final class TNot extends Token
{
    public TNot()
    {
        super.setText("NOT");
    }

    public TNot(int line, int pos)
    {
        super.setText("NOT");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNot(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNot(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNot text.");
    }
}
