/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.node;

import br.ufal.ic.se.analysis.*;

public final class TOr extends Token
{
    public TOr()
    {
        super.setText("OR");
    }

    public TOr(int line, int pos)
    {
        super.setText("OR");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TOr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOr(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TOr text.");
    }
}
