/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.node;

import br.ufal.ic.se.analysis.*;

public final class TRpar extends Token
{
    public TRpar()
    {
        super.setText(")");
    }

    public TRpar(int line, int pos)
    {
        super.setText(")");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRpar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRpar(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRpar text.");
    }
}
