/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.parser;

import br.ufal.ic.se.node.*;

public class ParserException extends Exception
{
    Token token;

    public ParserException(Token token, String  message)
    {
        super(message);
        this.token = token;
    }

    public Token getToken()
    {
        return token;
    }
}
