/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufal.ic.se.analysis;
import br.ufal.ic.se.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAAtomSentence(AAtomSentence node);
    void caseAComplexSentence(AComplexSentence node);
    void caseATruesentenceAtomicsentence(ATruesentenceAtomicsentence node);
    void caseAFalsesentenceAtomicsentence(AFalsesentenceAtomicsentence node);
    void caseASymbolAtomicsentence(ASymbolAtomicsentence node);
    void caseANegationComplexsentence(ANegationComplexsentence node);
    void caseAAndsentenceComplexsentence(AAndsentenceComplexsentence node);
    void caseAOrsentenceComplexsentence(AOrsentenceComplexsentence node);
    void caseAEntailssentenceComplexsentence(AEntailssentenceComplexsentence node);
    void caseABentailssentenceComplexsentence(ABentailssentenceComplexsentence node);

    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTNot(TNot node);
    void caseTEntails(TEntails node);
    void caseTBidientails(TBidientails node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTLpar(TLpar node);
    void caseTRpar(TRpar node);
    void caseTBlank(TBlank node);
    void caseTLetter(TLetter node);
    void caseEOF(EOF node);
}
